paypal/glamorous

- CONTRIBUTING.md
I noticed that `npm start "addContributor CompuIves"` didn't work, but `npm start "contributors.add"` does. This updates the documentation for it.
> Update the contributors command to "contributors.add"

- .all-contributorsrc
- README.md
This helps with #10.
**What**:
Added some style examples to the README. Some were taken from [this Medium post](https://medium.com/@kentcdodds/introducing-glamorous-fb3c9f4ed20e), others I just whipped up.
**Why**:
The examples in the article were helpful for knowing possibilities and syntax. Might as well make it easier to find.
**How**:
Added to the README.
> Add examples to README for different style objects

- .gitattributes
**What**:
With this inclusion git will attempt to keep multiple changes to a README to avoid conflicts
**Why**:
This is something I learned about [here](https://github.com/sindresorhus/refined-github/pull/23). That project had lots of changes to the README, and in `glamorous` the `all-contributors` might cause unnecessary conflicts. This could be nice to have and avoid merging/rebasing a PR.
**How**:
Small change in the `.gitattributes` file.
More info is available here: https://github.com/isaacs/github/issues/487
> chore(config): Add union merge strategy for README.md

- package.json
- rollup.config.js
- src/dom-elements.js
- src/index.js
- yarn.lock
**What**: This adds `rollup-plugin-json`
**Why**: Because we broke the rollup build when we started requiring packages that use `main` as a `json` file 😄 
**How**: add the plugin, also refactor things a little bit to be cleaner.
cc: @tsriram
> fix(umd): add json plugin

- README.md
- package.json
- rollup.config.js
- src/index.js
- src/react-compat.js
- yarn.lock
React@15.5.0 introduced deprecation warnings for a few things and they're really annoying. So this will help prevent those warnings from logging for people using this package.
> fix(react): add react-compat to deal with the warnings

- dist-test/index.js
- package-scripts.js
**What**: This adds a test for the distributable files
**Why**: #35 (make sure we don't break the way `glamorous` is exported/imported)
**How**: Copied a bunch of stuff from [`match-sorter`](https://github.com/kentcdodds/match-sorter)
Closes #35
> test(dist): add dist-test

- src/index.js
**What**: This adds an `if` statement to exit early in the `splitProps` function
**Why**: If the rootEl is a component, then we can forward all props to it without worrying about attaching props to DOM nodes. So we can skip the reduce function entirely.
**How**: Running the tests in watch mode and hitting random keys until they passed.
Helps with #43
> feat(perf): exit early when filtering props

- README.md
- src/__tests__/__snapshots__/with-theme.js.snap
- src/__tests__/with-theme.js
- src/index.js
- src/with-theme.js
- yarn.lock
**What**:
Added a HOC (higher order component) called `withTheme` that exposes theme context as a prop to passed in component.
**Why**:
It was requested in Issue #41 
**How**:
I first created a new file to contain the HOC, I then added to global exports. I also added tests.
There are a few comments in there as some things are unclear still. Mainly, what do we want to do when there is no context found (no ThemeProvider further up the tree). There is also some concern on naming of things. Not sure what you want the exported HOC class name to be.
> feat(HOC): add `withTheme` HOC

- README.md
- package.json
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/index.js
- yarn.lock
**What**: This adds a `forwardProps` option to the `glamorous` function
**Why**: So if you're wrapping a component in `glamorous`, you can specify some props to forward, regardless of the `rootEl` you define.
**How**: TDD! Also I had to update some dependencies to get rid of annoying warnings from React :)
> feat(forwardProps): add forwardProps option

- README.md
As pointed out by @mxstbr, we should include a note about the `glamor` requirement when talking about size.
> docs(size): add glamor badge for size

- test/glamorous.test.tsx
- typings/element-interfaces.d.ts
- typings/glamorous.d.ts
- typings/styled-function.d.ts
**What**:
Pulled in the excellent changes from https://github.com/paypal/glamorous/pull/56 by @sammkj, with minor modifications to retain autocomplete on common use cases.
**Why**:
> Some of the TS definitions don't match with current implementation. For example, glamorous takes in
> any number of style object and function. But the type definition only allows two arguments. Also,
> definition for glamorous returns incorrect type. This PR also adds definition for ThemeProvider
**How**:
By taking the changes from https://github.com/paypal/glamorous/pull/56 that did not end up getting merged.
> fix(typings): Update Typescript definitions

- README.md
Hi, I was playing around with some of the examples in the README.md in CodeSandbox and noticed this.
Not sure if this is an error in the docs or a bug but removing the array fixed the issue.
[![CodeSandbox example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/Vm43o6kZX)
**What**: README.md
**Why**: Example not working.
**How**: Remove array from example.
> Fix ...styles example in the readme

- typings/css-properties.d.ts
- typings/element-interfaces.d.ts
**What**:
There are lots of CSS rules that could have better typings. Therefore, I took [the interface `CSSProperties` from @types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts) (the interface that we use now) and did my best to improve it. Basically, I checked every prop in CSS reference on MDN and improved the prop type so that it matches its formal syntax.
Example:
```ts
type CSSWideKeyword = 'initial' | 'inherit' | 'unset'
...
// before
fontKerning?: CSSWideKeyword | any;
// Formal syntax on MDN: auto | normal | none
// https://developer.mozilla.org/en-US/docs/Web/CSS/font-kerning#Formal_syntax
// now
fontKerning?: CSSWideKeyword | 'auto' | 'normal' | 'none'
```
For many props it is not possible to get proper typechecking. Example is …
> feat(typescript): improved css props typings

- test/glamorous.test.tsx
- typings/glamorous.d.ts
**What**:
There are two little fixes in this PR.
Firstly, I forgot to apply new CSSProperties typings (#94) to extended components (e.g. `const MyAwesomeLink = glamorous(MyLink)({ color: 'red' })`). It was still using the React ones. Fixed now. Sorry for that, overlooked it :).
Secondly, the tests were broken. Actually, the new typings revealed it (yey 😀). Fixed.
**Why**:
Because we want good typings
**How**:
Pretty easily! See the commits.
@luke-john @sammkj Would you review it :)?
PS: @luke-john I don't know why, but I can't you add as a reviewer, weird 😕.
> fix(typescript): fixed typings tests and typings for extended component

- package.json
- src/__tests__/should-forward-property.test.js
- src/should-forward-property.js
**What**:
This is an attempt to fix https://github.com/paypal/glamorous/issues/91. Currently, we only support SVG attributes on the `svg` element. This updates the library to support all of them.
**Why**:
React supports many SVG attributes that need to be forwarded to SVG elements other than `svg`.
**How**:
Check if the tag belongs to a SVG element and if so, check if it's one of the React-supported SVG attributes. 
Currently, this branch is not passing all the tests because some HTML elements share the same tag names with some SVG elements. So don't merge it obviously. Let's discuss what's the best way to deal with situations like that.
> Support SVG-specific attributes for all available SVG tags

- src/index.js
**What**:
Fix for https://github.com/paypal/glamorous/issues/89
**Why**:
Rollup compilation results in glamorous unable to be used when compiled with typescript.
https://github.com/Microsoft/TypeScript/issues/13017#issuecomment-268657860
> fix(typescript): updated entry file for typescript consumption

- README.md
Prepares the README with a link to `glamorous-native` (re https://github.com/paypal/glamorous/issues/7#issuecomment-301961710)
This is introduced as a subsection to the installation documentation (taking a cue from `redux`'s complimentary `react-redux` package [in their README](https://github.com/reactjs/redux#complementary-packages)).
Let me know if there's anything else to add, or if should get its own section with any additional content.
If we were to do it differently, I could see a "Complimentary Packages" section, but perhaps in the future if more sibling packages surface.
> docs(readme): link to glamorous-native project

- typings/glamorous.d.ts
- typings/styled-function.d.ts
This is necessary for certain properties to work within the `css` prop object, such as `flexDirection`. Otherwise, you need to do something like this:
```jsx
<Div css={{ flexDirection: 'row' as 'row', }}>My Div</Div>
```
**What**:
Typescript support
**Why**:
Otherwise, weird TS errors when using certain properties within `css`
**How**:
Recursive type for `css`
> Add type for `css` prop

- other/manual-releases.md
**What**: This adds a `manual-releases.md` file
**Why**: Because sometimes weird things happen, and we want to be able to trigger a release in those cases.
**How**: GitHub :)
There was an issue with a minor release, so this manual-releases.md
change is to release a new minor version.
Reference: #113
> feat(release): manually release a minor version

- .gitignore
- package.json
- test/glamorous.test.tsx
- tsconfig.json
- typings/glamorous.d.ts
**What**:
This adds the `ExtraGlamorousProps` type as a top-level export and adds a test for the underlying TypeScript issue it works around.
**Why**:
This fixes issues when using TypeScript with `"declaration": true` in combination with webpack.
Original TypeScript issue: https://github.com/Microsoft/TypeScript/issues/5938
> [ts] Exported variable 'StyledPromiseCard' has or is using name 'ExtraGlamorousProps' from external module "[...]/node_modules/glamorous/typings/styled-function" but cannot be named
One workaround of this issue is to explicitly import the misbehaving type:
```ts
import glamorous from 'glamorous'
import { ExtraGlamorousProps } from 'glamorous/typings/styled-function'
```
This does however break the module resolution in our webpack build for Node.JS and throws "Module …
> fix($typescript): Add ExtraGlamorousProps type as top-level export

- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/__snapshots__/theme-provider.js.snap
- src/__tests__/index.js
- src/__tests__/theme-provider.js
- src/__tests__/tiny.js
- src/create-glamorous.js
- src/get-glamor-classname.js
**What**: `context` is now accessible in dynamic style functions
```js
const MyDiv = glamorous.div(
(props, context) => ({ /* style from context */ })
)
MyDiv.contextTypes = { /* user context types */ }
```
**Why**: See goals in #125, previously `context` was inaccessible by `glamorous` dynamic styles
**How**: The `GlamorousComponent` now [passes `context` to `getGlamorClassName`](https://github.com/robinpowered/glamorous/blob/c96f7aaf30b2a7d7910d6cb44f9ba217397f9fd5/src/create-glamorous.js#L103) instead of `theme`, which [passes the `context` along to the dynamic style function](https://github.com/robinpowered/glamorous/blob/c96f7aaf30b2a7d7910d6cb44f9ba217397f9fd5/src/get-glamor-classname.js#L35).
The `theme` is still in the picture: we [add it to the …
> feat(context): add dynamic style context support

- README.md
- other/TYPESCRIPT_USAGE.md
closes #83 
**What**:
Added usage notes and known issues for typescript
**Why**:
The current bundled typescript definitions are incomplete and based around the needs of the developers who contributed them.
Whilst this is true of the definitions of many non typescript projects, it could still be a pain point for consumers.
**How**:
Based on feedback of #83 
**Checklist**:
> docs($typescript): added typescript usage notes and known issues

- README.md
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/create-glamorous.js
- src/index.js
**What**: Closes #137
**Why**: This makes it easier to know which elements map to which glamorous components.
**How**:
- Change the `className` to include the `GlamorousComponent.className`
**Checklist**:
> feat(className): add displayName to the className

- test/glamorous.test.tsx
- typings/glamorous.d.ts
- typings/styled-function.d.ts
BREAKING CHANGE: The updated theme typing will complain if existing usage of theme is unsafe
**What**:
Updated the typings around themes to get better safety around usage
**Why**:
We're implementing theming in a component library and wanted safety.
**How**:
Updated the typescript definition files and tests.
**Checklist**:
> feat(typescript): Improved theme typing and tests

- README.md
- package.json
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/get-glamor-classname.js
- src/umd-entry.js
- yarn.lock
**What**: Closes #170
**Why**: enables code reuse and potentially "Ahead of Time compilation"
**How**:
- Reusing the same logic for `cssOverrides` as we use for
`styles` in `get-glamor-classname.js`. Tiny refactor there.
- Adding tests to cover all the cases for the API.
**Checklist**:
I also updated deps because I think prettier was messed up.
> feat(css): allow the `css` prop to accept fns and strings

- other/TYPESCRIPT_USAGE.md
- test/glamorous.test.tsx
- typings/glamorous.d.ts
**What**:
Added missing typing for config, .
**Why**:
We're adding displayNames to aid in development and noticed this type was missing
**How**:
**Checklist**:
I noticed that the tslint is currently broken against the typescript files.  I'll open a seperate issue for that.  Might be worth using prettier on the types and tests to bring it into line with the core project now prettier has typescript support.  Have opened https://github.com/paypal/glamorous/issues/172 to investigate and resolve.
> chore(typescript): Added config to typings

- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/create-glamorous.js
- src/get-glamor-classname.js
- src/split-props.js
- src/tiny.js
I'm working on fixing a bug I found while making [this](https://codesandbox.io/s/ERNVNoxEv) (notice that the `textAlign="center"` is not applied to the first user card because the `css` prop is set to a function.
As part of making that an easier fix, I'm refactoring `getGlamorClassName` and I'm not sure why a bunch of the tests are breaking. I've only dug a little ways into it, but now I've got daddy duty. If anyone wants to debug it and figure out what's up, that'd be awesome. At first glance, it appears that the class names are generated properly, but somehow they're not added to glamor's stylesheet which is why they're not appearing in the snapshot???? Weird stuff.
> fix(css): improve built-in support with css prop as function

- dist-test/index.js
- package.json
- src/__tests__/index.js
- src/__tests__/with-theme.js
- src/create-glamorous.js
- src/with-theme.js
**What**: This changes the GlamorousComponent from a class to a function that uses `withTheme`.
**Why**: This simplifies the codebase and prepares us for potentially dropping our own theming implementation in favor of the `theming` module.
**How**: Refactoring `withTheme` to have all the features that the glamorous component had and wrapping the glamorous component in `withTheme`.
This change _should_ be totally non-breaking despite some of the test changes. I'd really appreciate a review on this one from folks.
> chore(theme): swap custom theme code with `withTheme`

- test/glamorous.test.tsx
- tslint.json
- typings/glamorous.d.ts
**What**:
Corrects the type (typescript) for the withTheme higher component
**Why**:
**How**:
**Checklist**:
> fix(typescript): Correct type for the withTheme higher order component

- other/codemods/README.md
- other/codemods/__snapshots__/theme-move.test.js.snap
- other/codemods/package.json
- other/codemods/theme-move.js
- other/codemods/theme-move.test.js
**What**: This adds a codemod. It's still a work in progress
**Why**: To help people upgrade
**How**: A lot of help and inspiration from @tdeschryver
**Checklist**:
We need more test cases! There are definitely code styles that this doesn't handle. We should also probably consider the `css` prop which can accept dynamic style functions as well.
> add codemods

- other/TYPESCRIPT_USAGE.md
- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- test/should-fail.test.tsx
- typings/glamorous.d.ts
**What**:
Remove useDisplayNameInClassName and config
**Why**:
Because they are being removed from the glamorous api
https://github.com/paypal/glamorous/pull/247
**How**:
**Checklist**:
This also contains a commit which fixes a seperate issue in the `glamorous.test.tsx` which had managed to sneak into the snapshot as well.
> task(typescript): remove useDisplayNameInClassName and config

- README.md
- docs/FAQ.md
- examples/with-jest/index.test.js
- examples/with-jest/testSetup.js
- package.json
- src/__tests__/__snapshots__/dev.js.snap
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/create-glamorous.with-component.js
- src/__tests__/dev.js
- src/__tests__/index.js
- src/__tests__/theme-provider.js
- src/__tests__/tiny.js
- src/create-glamorous.js
- src/get-glamor-classname.js
closes #242
BREAKING CHANGE: It is no longer possible to configure anything with glamorous
**What**: remove useDisplayNameInClassName and use glamor's built-in `label` instead
**Why**: it's better
**How**:
- Removed docs for config
- added a `dev.js` to test this feature
- accept `displayName` in `getGlamorClassName` and add a `{label: displayName}` for every call to glamor's `css` function.
**Checklist**:
> fix: remove useDisplayNameInClassName and use glamor's built-in `label`

- other/TYPESCRIPT_USAGE.md
- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- test/should-fail.test.tsx
- typings/built-in-component-factories.d.ts
- typings/component-factory.ts
- typings/glamorous-component.d.ts
- typings/glamorous.d.ts
**What/Why**:
Adds support for https://github.com/paypal/glamorous/pull/250
**How**:
Updated the typing to accept `shouldClassNameUpdate`. 
**Checklist**:
I also fixed an unrelated issue around looseness in the typing of component factories creation where when passed a component glamorous did not automatically work out it's Props as this issue was making it hard to test.
> feat(typescript): add shouldClassNameUpdate typing

- other/TYPESCRIPT_USAGE.md
- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- test/should-fail.test.tsx
- typings/built-in-component-factories.d.ts
- typings/component-factory.ts
- typings/glamorous.d.ts
**What**:
Provides support for glamorous component factories to be created with dom keys
https://github.com/paypal/glamorous/tree/6d806889e9991065f1243d4abdce9c0b6cd3a2ae#using-glamorous-composition
ie. `glamorous('div')`
**Why**:
**How**:
Added two new overloads to the `GlamorousInterface` for HTML and SVG tagsthat are typed to provide the same return type as the built-in glamorous component factories.
**Checklist**:
This topic branch is based off https://github.com/paypal/glamorous/pull/251.
https://github.com/luke-john/glamorous/commit/1b4413ce9a90c153a85531c95282ca4722375e7b is the only unique commit
> feat(typescript): create component factories via dom key

- README.md
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/create-glamorous.js
**What**: expose `propsAreCssOverrides` and composition
**Why**: Closes #256
**How**:
- adding `propsAreCssOverrides` to the options provided to the `glamorousComponentFactoryFactory` and defaulting that to the `component.propsAreCssOverrides`
- Testing it
**Checklist**:
> feat: expose propsAreCssOverrides and composition

- README.md
- src/__tests__/__snapshots__/index.with-props.js.snap
- src/__tests__/index.with-props.js
- src/create-glamorous.js
**What**: This adds the `withProps` helper API
**Why**: Closes #133 
**How**:
- Store the `propsToApply` on the `GlamorousComponent`
- expose a way to create a new glamorous component that combines the `propsToApply` given.
- When rendering, reduce all the `propsToApply` with the `props` given to a single props object
**Checklist**:
> feat(withProps): add `withProps` helper API

- other/TYPESCRIPT_USAGE.md
- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- test/should-fail.test.tsx
- typings/component-factory.ts
- typings/glamorous-component.d.ts
- typings/glamorous.d.ts
**What and Why**:
This adds the typing required to use the new `withProps` helper API
introduced by https://github.com/paypal/glamorous/pull/255/files.
**How**:
Adding withProps to the GlamorousOptions with a generic type that is also passed to the ComponentFactory allowing the typing to be automatically inferred on usage.
**Checklist**:
> feat(typescript): add typing for `withProps` helper APIi

- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- test/should-fail.test.tsx
- typings/css-properties.d.ts
- typings/helpers.d.ts
- typings/svg-properties.d.ts
**What**:
Adding typing for styles to accept arrays
**Why**:
As reported in #259 glamor accepts array values and uses them to create fallback values
https://github.com/threepointone/glamor/blob/00349761d9ee56c781dff448b3a9979e3d05e042/docs/howto.md#fallback-values
**How**:
Adding typings and tests.
**Checklist**:
> feat(typescript): accept property arrays for fallbacks

- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- test/should-fail.test.tsx
- typings/component-factory.ts
- typings/glamorous.d.ts
Noticed the theme was still being passed as a seperate generic when doing a screen capture for the release notes.
https://github.com/paypal/glamorous/pull/230#issuecomment-318878595
This behaviour is left over from when theme was passed as a seperate argument and had already been removed in some of the typing
**What**:
Removing all typings that had Theme as an additional generic to Props 
**Why**:
Simplifies Theme usage
**How**:
Updated the component factory typings to add overloads for components that make use of Theme
**Checklist**:
> chore(typescript): consistant theme handling

- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- test/should-fail.test.tsx
- typings/component-factory.ts
- typings/glamorous.d.ts
- typings/style-arguments.d.ts
**What and Why**:
Adds typing for https://github.com/paypal/glamorous/pull/258/files
**How**:
Added overloads to the glamorous interface to use a glamorous component factory typing which adds the Properties on the external when `propsAreCssOverides` is enabled.
**Checklist**:
> chore(typescript): add typing for propsAreCssOverides

- test/glamorous.test.tsx
- typings/css-properties.d.ts
- typings/svg-properties.d.ts
**What and Why**:
Fixs a typing issue with style objects which prevented multi level nested keys, also added tests to prevent breaking again in future.
ie
```js
{
':hover': {
'& .vendor-class': {
height: '10px',
}
}
}
```
**How**:
Added `PropertiesLossy` (the string indexer that is used to allow these keys) as an acceptable type for itself.
**Checklist**:
> fix(typescript): property nesting beyond one level

- test/glamorous-exports.test.ts
- typings/glamorous.d.ts
**What**:
Re export all css and svg types from the main definition file.
**Why**:
It's often quite handy to use these when setting up helper methods.
ie.
```ts
import { CSSPropertiesComplete } from 'glamorous'
type GetExecutionStyles = (execution: 'execution-one' | 'execution-two') =>
CSSPropertiesComplete
const getExecutionStyles: GetExecutionStyles = (execution) => {
// ... build up a styles object which returns CSSPropertiesComplete
return styles
}
glamorous('div')(
getExecutionStyles('execution-one')
)
```
**How**:
**Checklist**:
> chore(typescript): re export all css and svg types

- test/glamorous.test.tsx
- typings/component-factory.ts
**What**:
Props passed to glamorous component factories were not being set as external props on some glamorous components.
**Why**:
Because it was broken.
**How**:
Pass these props to the Glamorous Component which adds them to the external props intersection type.
**Checklist**:
> fix(typescript): fix missing props on glamorous components

- src/__tests__/create-glamorous.with-component.js
- src/create-glamorous.js
**What**: This forwards _all_ properties from the subject component to
the newly created component.
**Why**: To ensure that the new component is basically everything that
the old one was except a new target component to render.
**How**: Spreading component properties.
**Checklist**:
I'd really appreciate a review from at least one person on this. The impact is any time you call `.withComponent` it should do what you probably thought it already did. But we _are_ changing behavior here slightly so I'd like to get this reviewed.
My use case was:
```javascript
const FadedText = Text.withProps({fadedExtra: true})
const Description = glamorous(FadedText)({
margin: '0 0 10px',
}).withComponent('p')
```
The `propsToApply` of `{fadedExtra: true}` was not getting applied to the component returned …
> fix(withComponent): maintain component properties

- package.json
- src/__tests__/.eslintrc
- src/__tests__/index.with-config.js
- src/create-glamorous.js
I noticed that
[the styled-components babel plugin](https://github.com/styled-components/babel-plugin-styled-components/blob/37a13e9c21c52148ce6e403100df54c0b1561a88/src/visitors/displayNameAndId.js)
sets the `displayName` by using a `withConfig` function and I thought
that was a pretty good idea. So I'm adding this as an undocumented
feature (because I don't think people will really need to use it outside
the babel plugin)
**Checklist**:
> feat(withConfig): add (undocumented) `withConfig` for tooling

- src/__tests__/__snapshots__/typescript.js.snap
- typings/component-factory.ts
- typings/style-arguments.d.ts
**What**:
Glamorous component factory typings are now overloaded to accept
arguments in the following order of matching:
* style arguments with no Props
* style arguments with Props and a Theme
* style arguments with Props
**Why**:
Makes a huge difference to the amount of memory being used by glamorous and hopefully solves the out of memory issue reported at https://github.com/paypal/glamorous/issues/288.
**How**:
Fixing the existing overloads and adding a new one for glamorous components that do not use Props or Theme. 
**Checklist**:
> fix(typescript): fix component factory typings

- package.json
- src/__tests__/__snapshots__/typescript.js.snap
- test/glamorous.test.tsx
- typings/built-in-component-factories.d.ts
- typings/css-properties.d.ts
- typings/glamorous-component.d.ts
- typings/style-arguments.d.ts
- typings/svg-properties.d.ts
**What**:
Improvements to the typings to give better parameter hints.
**Why**:
The current typings use types in a number of places which results in enormous parameter hints in vscode and online editors using monaco such as codesandbox and stackblitz.
**How**:
Replaced a number of types with interfaces and removed unneeded Partials.
**Checklist**:
Note:
Converting the `GlamorousComponent` from a type -> interface means that when generating definitions users will now need to re-export `GlamorousComponent` rather than `ExtraGlamorousProps`.
> chore(typescript): improve typescript dx

- src/__tests__/__snapshots__/typescript.js.snap
- typings/dom-tag-component-factory.d.ts
- typings/glamorous.d.ts
**What**:
Fixes dom-tag component factories and also cleans up parameter hints for components created in this style.
**Why**:
When glamorous component factories are created from strings currently they incorrectly union all Dom Element interfaces. 
**How**:
Extended the Glamorous interface with two new interfaces (`DOMTagComponentFactory` + `SVGTagComponentFactory`) which add overloads to the glamorous interface for component factories created with all dom-tag keys.
**Checklist**:
Parameter hinting with correct dom-tag component factory typing:
Parameter hinting with current incorrect dom-tag component factory typing:
I'm likely to open a couple of additional PRs this afternoon based off this one which continue the effort started in https://github.com/paypal/glamorous/pull/301 to improve …
> fix(typescript): fix type of component factories created from strings

- package.json
Fix the `"module"` and `"jsnext:main"` package.json entries to reference the actual built `dist/glamorous.esm.js` file. See [glamorous build 4.9](https://unpkg.com/glamorous@4.9.0/dist/).
This allows glamorous to build with Rollup.js's support for ES6 "module" entries.
> Fix package.json `module` to use ".esm.js" extensions

- src/__tests__/create-glamorous.with-component.js
- src/create-glamorous.js
**What**: This adds `object` as an option for `className` to allow for passing `glamor.css` to the `className` prop.
**Why**: This closes #332
**How**: `PropTypes.oneOfType`
**Checklist**:
cc @Tibfib and @marzelin
> fix(propTypes): allow object as className

- package.json
The `test:ts` script was being used previously to test that the
typescript definitions were working correctly.  These were moved
into the main tests to allow snapshots to be maintained with
extra tests which ensure the defintions fail on incorrect usage
of glamorous.
**What/How**:
remove deprecated npm script `test:ts`
**Why**:
It now fails with the should-fail test file.
**Checklist**:
closes #335
> fix(typescript): remove deprecated npm script

- src/__tests__/__snapshots__/theme-provider.js.snap
- src/__tests__/theme-provider.js
- src/theme-provider.js
**What**:
This fixes a bug when having nested `ThemeProvider`s and updating outer theme the change is not reaching the `StyledComponent`
```jsx
<ThemeProvider theme={{}}>
<ThemeProvider theme={{}}>
<StyledComponent>
</ThemeProvider>
</ThemeProvider>
```
**Why**:
This is a bug fix.
**How**:
Using publish in the nested `ThemeProvider`s subscriptions.
**Checklist**:
Repro provided by @mitchellhamilton - https://codesandbox.io/s/6j42qx5z23
> Fixed nested themes not being republished on outer theme changes

- typings/css-properties.d.ts
- typings/glamorous-component.d.ts
**What**:
Fixes the type definitions for `css` prop. The `css` prop actually accepts either an object or an array of nested objects/arrays.
**Why**:
TypeScript support
**How**:
Leverage recursive types described in this comment: https://github.com/Microsoft/TypeScript/issues/3496#issuecomment-128553540
**Checklist**:
The build fails due to previous failure. I have PR #382 that fixes this.
> TypeScript: Add recursive array type to CSS prop

- .gitignore
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/index.js
- src/get-glamor-classname.js
This approach simply unwinds functions until it gets a non-function, then recurses normally.
**What**:
Style function recursion. Closes #390 
**Checklist**:
> CSS function recursion
