- .all-contributorsrc
- README.md
- other/EXAMPLES.md
Add an interactive example to examples section.
So users can try the examples in an interactive way.
By adding a url 🙃
> Add CodeSandbox preview to example

- .all-contributorsrc
- README.md
- src/__tests__/index.js
**What**: feature
**Why**: makes it easy to read
**How**: added proper styles to elements on comments
> Fix style on comment

- .all-contributorsrc
- CONTRIBUTING.md
- README.md
in CONTRIBUTING.md @ line:39 comitted was changed to committed
**What**:
**Why**:
**How**:
> docs(CONTRIBUTING.md): comitted was changed to committed

- .all-contributorsrc
- README.md
**What**: Just a broken link of the LICENSE in the README.md
**Why**:
**How**: Changed the URL
> Fix broken license link

- README.md
**What**: Adds a link to a codesandbox that demos the `ThemeProvider`
**Why**: To make it easier for people to get started.
**How**: The magic of codesandbox :)
> docs(theme): add example for theme

- examples/README.md
**What**: Added link to example with create-react-app
**Why**: Better documentation
**How**: Added link to the repository
> docs(examples): Add example with create-react-app

- package.json
- tslint.json
- typings/glamorous.d.ts
- typings/glamorous.test.tsx
- yarn.lock
**What**:
Wrote some basic TS definitions. This only covers `glamorous` function.
**Why**:
Because every good lib deserves type definitions.
**How**:
Styled-components type definitions were referred when writing these definitions.
> Add basic Typescript definitions

- .all-contributorsrc
- README.md
**What**:
Fixed an error in the docs for `withTheme` example. I fixed in code sandbox example and wanted to reflect the correct example here as well. Also added myself to contribs since I forgot to add to `withTheme` PR.
**Why**:
If a user copied the example for `withTheme` it would not work properly.
**How**:
Updated README
> fix(docs): fix `withTheme` example, add kkemple to contributors

- .all-contributorsrc
- README.md
**What**: Fix minor typos in `README.md.`
**Why**:  💄 glamorous deserves 💄 glamorous docs.
**How**: `vim` 🤔
@kentcdodds Thanks for everything you've done in the community. You're one of the biggest reasons that I want to get involved with OS! 👍
> docs(cleanup): Fix typos in README.md

- CONTRIBUTING.md
As we recently agreed on the format to deal with examples for glamorous, this will document it.
BREAKING CHANGE: None
#34
> docs(examples): Add documentation to create examples

- README.md
typo in readme 
newcomers trying to grok the code
fixed the typo
> :pencil2: typo

- package-scripts.js
- package.json
- rollup.config.js
- src/__tests__/index.js
- src/index.js
- yarn.lock
**What**: This takes some of the ideas from @developit to make the glamorous component render method faster
**Why**: Because that's some hot code!
**How**: copy/paste and blindly looking for other things I figured could be faster...
Ref #43
> feat(perf): improve performance of GlamorousComponent#render

- package.json
- yarn.lock
**What**:
Updated the minimum version of `react-html-attributes` because some react specific attrs such as `noValidate` are missing.
**Why**:
The latest version of that package fixes the omission of some react specific attributes.
> Update react-html-attributes version to fix omission of some react specific attributes

- other/USERS.md
Adding RestoNGo to USERS.md
I hope I am not too verbose compared to the others. I can cut the end if you think it's unnecessary.
> Add RestoNGo to USERS.md

- typings/css-properties.d.ts
**What**: Adds "box-sizing" to TypeScript typings files
**Why**: Completions/typings for "boxSizing"/"box-sizing" were missing from this project. Many of the related properties were present, so I assumed this was an oversight and wanted to correct it.
**How**: Added a line/definition to the typings file. Also added a comment and link to MDN.
> Adds box-sizing typings and possibe values

- .github/PULL_REQUEST_TEMPLATE.md
**What**: Adds a checklist to the pull request template
**Why**: reminds us all of what should go into PRs
**How**: GitHub's editor for `.github/PULL_REQUEST_TEMPLATE.md`
> docs(pr): add a checklist to pull request docs

- other/MAINTAINING.md
**What**: add `other/maintaining.md`
**Why**: So other folks who are helping to maintain the library know how things work
**How**: GitHub editor to add the file.
**Checklist**:
- ~~[ ] Tests~~
- ~~[ ] Code complete~~
> docs(maintaining): add maintaining documentation

- README.md
**What**: Added a swag section to the bottom of the readme with two links to t-shirts.
**Why**: 
**How**: Modifying the README.md file.
**Checklist**:
Thanks for letting us put a couple T-Shirts up for the project!
> add swag section to README.md

- README.md
- src/__tests__/__snapshots__/index.js.snap
- src/__tests__/__snapshots__/theme-provider.js.snap
- src/__tests__/index.js
- src/__tests__/theme-provider.js
- src/__tests__/tiny.js
- src/create-glamorous.js
- src/get-glamor-classname.js
**What**: Changing the implementation of #128
**Why**: As discussed in #125
**How**:
- Remove/change unnecessary tests
- Update the implementation to pass both theme and context.
**Checklist**:
> feat(context): move context to a third parameter

- CONTRIBUTING.md
**What**:
Added mention that you must use node v6 as a contributor.
**Why**:
Tests don't pass unless you're running node v6 :)
**Checklist**:
> docs(contributing): mention node v6 requirement

- README.md
Because this is a PayPal project and I am sorta already paid to work on it 😅
> chore(badges): remove donate badge

- other/USERS.md
**What**:
Added The West Australian to users.
**Why**:
**How**:
We landed glamorous in prod 💯 .
**Checklist**:
> docs(users): Added The West Australian to users

- package.json
- yarn.lock
**What**:
Moved doctoc to dev dependencies
**Why**:
The doctoc dependency introduced quite a few transitive dependencies.
**How**:
**Checklist**:
> chore(dependencies): Shifted doctoc to dev dependencies

- examples/README.md
- examples/with-jest/README.md
Hello folks,
**What**: Improve documentation
**Why**: I had trouble finding how to test glamorous components with Jest (specially in a create react app environment)
**How**: Use existing example and jest+cra documentation to find the right working solution
**Checklist**:
I certainly will make others PR to improve documentation about testing (and looking for the website too!).
The main readme does not mention test, I find that this is lacking.
> Improve documentation about Jest testing

- README.md
- docs/FAQ.md
Hi all, adding a FAQ section and updated the README to link it.  Feel free to make any changes as I'm the best writer.
> Adding FAQ.md and updated README.md

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- package-scripts.js
- package.json
**What**: Update contributing docs, remove some dependencies
**Why**: This will make it easier to contribute to the library
**How**:
- Remove `validate-commit-msg` and `commitizen`. We can change the commit message anyway, and the script doesn't even run for the people who are probably getting it wrong anyway, so I don't see much reason to keep it. Commitizen has really only made things more complicated for all my OSS stuff, so I'll be removing it from my generator eventually too.
**Checklist**:
I'd love this to be reviewed quickly, but if nobody has time I'm going to merge it because I want to make a `first-timers-only` issue in a minute :smile:
> chore: general repo cleanup

- other/USERS.md
**What**:
Added EDITED to users
**Why**:
Showing the support!
**How**:
**Checklist**:
> docs(users): Added EDITED to users

- README.md
**What**: Centers things the way @tkh44 centers things in the [emotion](https://github.com/tkh44/emotion) README
**Why**: Because when I saw it I thought it looked great
**How**: Mostly copy/paste/modify
**Checklist**:
> docs(README): center things and update tagline

- index.js
- package-scripts.js
- package.json
- yarn.lock
**What**: This re-enables bundlesize
**Why**: Because I was told that someone in the PayPal admin group enabled it
**Checklist**:
> chore: enable bundlesize

- other/USERS.md
**What**:
**Why**:
**How**:
**Checklist**:
> add Songlink to list of glamorous users

- README.md
> Update styled applied comments

- README.md
- src/__tests__/index.should-class-name-update.js
- src/create-glamorous.js
**What**: add `shouldClassNameUpdate` for optimizing glamorous components
**Why**: Closes #203
**How**:
- Add a function to implement this and return `true`/`false` as the case may be
- only compute the className if needed
- Add a test for this functionality
**Checklist**:
> feat: add shouldClassNameUpdate for optimizing glamorous components

- other/USERS.md
Saw in the blog post there's a users file. Forgot about this -- adding Robin
> Add Robin to Users.md

- README.md
**What**: Added vscode extension link to `README.md`
**Why**: 
**How**:
**Checklist**:
> added link for vscode extension

- README.md
**What**: Added `glam-atom` to related projects
**Why**:
**How**:
**Checklist**:
> Atom extension

- other/FAQ.md
**What**: Adding A brief `Vs Css Modules section`
**Why**: They aren't necessary, however I wished I would have had them when I first discovered the library
**How**: Added to the FAQ
**Checklist**:
- [NA] Documentation
- [NA] Tests
I'm still very new to Glamorous, so I'm sure I'm missing essential differentiating factors. I didn't mention composition of styles because CSS modules can do that (even though it's different)
This PR is in hopes that my brief start will help others see the differences and make wise decisions on what libraries they plan on using.
> Adding a small `Vs CSS-Modules` section to the FAQ

- README.md
**What**:  Added [`glamorous-redocx`](https://github.com/nitin42/glamorous-redocx)
**Why**:
**How**: Added to projects section
**Checklist**:
Woah! with `glamorous-redocx`, glamorous has become more awesome. Now glamorous can be used to style the components and render them in any host environment. Mobile, web, sketch and word document. Tweet about how powerful glamorous has become 😄
> added glamorous-redocx

- test/glamorous-exports.test.ts
- test/glamorous.test.tsx
- typings/glamorous-component.d.ts
- typings/glamorous.d.ts
**What**: TypeScript type for props of glamorous component.
**Why**: For testing or for storybook, sometime we need general props
**How**: Follow my codes on https://github.com/paypal/glamorous/issues/292
**Checklist**:
> feat(typescript): add type for props of glamorous component

- README.md
**What**: Added new section for usage with react-sketchapp
**Why**: To make glamorous more awesome 😆 . Ohk! These changes are necessary to showcase the glamorous usage with react-sketchapp
**How**: Added links and resources.
**Checklist**:
> added new section for react-sketchapp

- .github/ISSUE_TEMPLATE.md
**What**:
Added some notes to the issue template for reports to do with typescript.
**Why**:
To make it easier for people using glamorous with typescript to report issues.
**How**:
Setup a typescript stackblitz playground for people to create reproductions of issues.
The stackblitz playground is a near exact copy of the codesandbox help playground, with the one exception of a return type being added to the `gradientText` function.
**Checklist**:
> chore(typescript): update issue template with typescript notes

- README.md
Yeah! Now we can use Stylus with glamorous 😄. Tweet about it !!
**What**: Added link for glamorous-stylus
**Why**: To support Stylus
**How**: Added link for repo and documentation
**Checklist**:
> glamorous-stylus

- typings/css-properties.d.ts
**What**: Adding `borderRadius` to TS typing
**Why**: borderRadius is general CSS property
**How**: You know, just adding it.
**Checklist**:
> fix(typescript): fix CSSProperties type by adding borderRadius

- other/USERS.md
**What**:
**Why**:
**How**:
**Checklist**:
> add Budgee to list of users

- other/USERS.md
**What**:
Add [Mineral UI](http://mineral-ui.com/) to list of Glamorous users
**Why**:
To share that Mineral UI is part of the Glamorous community
**How**:
Added an entry to `USERS.md`
**Checklist**:
> docs(users): Add Mineral UI to list of Glamorous users

- other/USERS.md
**What**:
Add [TABtouch](https://www.tabtouch.mobi) to users.
**Why**:
We 🚢 shipped our first 💄glamorous component to our production environment as part of our latest release this week. :shipit: 
**How**:
Team effort 😏 
**Checklist**:
Looking forward to glamorousing **all the things**!
> Add TABtouch to users

- typings/glamorous.d.ts
**What**:
Additional comments for typings.
**Why**:
As requested in #302 .
**How**:
Added comments directly to the code.
**Checklist**:
I've encountered a problem when running *add-contributor* script - and I believe it's related to incorrect username. Could you provide an example, please? I've tried email and nickname, both resulted in "Not found".
> docs: add comments to typings (#302)

- examples/with-jest/README.md
Reference jest-glamor-react in jest example.
**Why**:
so that people following this example are aware of this option sooner rather than later
**How**:
Update to documentation
**Checklist**:
> Reference jest-glamor-react in jest example

- other/USERS.md
**What**: Adds The Artling as a user
**Why**: Glamorous is awesome!
**Checklist**:
> Adds The Artling as a user of glamorous

- other/codemods/README.md
In response to #419, I added a link to a codemod I wrote that helps migrate existing React/Preact codebases to emotion from glamorous.
> Add codemod that migrates glamorous to emotion

- jest.config.js
- other/jest.config.js
- package.json
- src/__tests__/__snapshots__/typescript.js.snap
This just makes changes so `master` actually runs and the tests pass.
I'm going to publish a major version with a deprecation message.
> chore: update all things so it runs
